version: '3.9'

services:
  # API Gateway
  gateway:
    container_name: gateway
    build: .
    ports:
      - "8080:8080"
    networks:
      - Mynet  

# Docker Networks
networks:
  Mynet:
      external: true
      name: github.com/Time-Capsule/Auth-Service

      driver: bridge   
