name: Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pwd
          echo BOSHLANDIIIIIIIIIIIIIIIIIIIIIIIIIIi
          git clone git@github.com:IsakovDiyorbek/Time-Capsule.git
          cd Time-Capsule
          git pull origin main

          cd Api-Gateway
          git pull origin main
          sudo docker compose down
          sudo docker compose up -d --build
          sudo docker compose down
          sudo docker compose up -d

          cd ..
          cd Auth-Service
          git pull origin main
          sudo docker compose down
          sudo docker compose up -d --build
          sudo docker compose down
          sudo docker compose up -d

          cd ..
          cd Memory-Service
          git pull origin main
          sudo docker compose down
          sudo docker compose up -d --build

          sudo docker compose down
          sudo docker compose up -d 
